[package]
name = "rusty_store"
version = "0.1.0"
edition = "2021"

[dependencies]
tabled = "0.15"
dotenvy = "0.15"
inquire = "0.6.2"
clap = { version = "4", features = ["derive"] }
diesel = { version = "2", features = [
  "sqlite",
  "returning_clauses_for_sqlite_3_35",
] }
