CREATE TABLE sale_transactions (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  product_id INTEGER NOT NULL REFERENCES products(id),
  product_price DECIMAL(10,2) NOT NULL,
  sold_price DECIMAL(10,2) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0
);
